version: "2.4"

services:
  nginx:
    image: nginx:latest
    container_name: matomo_proxy
    depends_on:
      - db
      - app
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:Z
      - ./conf/ssl.conf:/etc/nginx/conf.d/ssl.conf:Z
      - ./keys:/etc/ssl/private:Z
    ports:
      - 80:80
      - 443:443
    restart: on-failure

  db:
    image: mysql:latest
    container_name: matomo_db
    volumes:
      - ./conf/setup-db.sql:/docker-entrypoint-initdb.d/setup-db.sql:Z
      - ./conf/in-file.cnf:/etc/mysql/conf.d/in-file.cnf:Z
    environment:
      - MYSQL_ROOT_PASSWORD=${mysql_root_password}
    cap_add:
      - SYS_NICE
    restart: on-failure

  app:
    image: matomo:latest
    container_name: matomo_app
    depends_on:
      - db
    volumes:
      - ./setup:/var/www/html:Z
    environment:
      - MATOMO_DATABASE_HOST=db
    env_file:
      - ./conf/db.env
    mem_limit: 4g
    restart: on-failure
